kind: Deployment
apiVersion: apps/v1
metadata:
  name: django-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-docker
  template:
    metadata:
      labels:
        app: django-docker
    spec:
      containers:
      - name: django-docker
        image: django_fintech_enterprise_container
        ports:
        - containerPort: 80