version: "3.8"
services:
  app:
    container_name: django_fintech_enterprise_container
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - db_network
      - web_network
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    image: app:django
    command:
      - /bin/sh
      - -c
      - |
        python3 manage.py makemigrations
        python3 manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A fintechengine worker -l INFO
    volumes:
      - .:/django
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
    depends_on:
#      - django
      - redis
  redis:
      image: "redis:alpine"
      container_name: redis_fintech_django
      ports:
        - '6379:6379'
      volumes:
          - redisDB:/data
  db:
    restart: always
    image: postgres
    container_name: fintech_enterpriseDB_postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fintech_enterpriseDB
      - POSTGRES_USER=joelwembo
      - POSTGRES_PASSWORD=abcde@12345
      - POSTGRES_PORT=5432
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    expose:
       - "5432"
    ports:
       - "5432:5432"
  pgadmin:
        restart: always
        image: dpage/pgadmin4
        container_name: fintech-pgadmin # you can change this
        depends_on:
          - db
        ports:
          - "5051:80"
        environment:
          PGADMIN_DEFAULT_EMAIL: joelotepawembo@gmail.com
          PGADMIN_DEFAULT_PASSWORD: abcde@12345

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge