version: "3.8"
services:
  app:
    container_name: django_fintech_enterprise_container
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - db_network
      - web_network
    volumes:
      - .:/django
    ports:
      - 8080:8080
    image: app:django
    command:
      - /bin/sh
      - -c
      - |
        python3 manage.py makemigrations
        python3 manage.py migrate
        #... Add any script at will...
        python isdkgfd.py
        
        python manage.py runserver 0.0.0.0:8080
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A fintechengine worker -l INFO
    volumes:
      - .:/django
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
    depends_on:
      - django
      - redis
  redis:
      image: "redis:alpine"

  nginx:
      container_name: nginx
      restart: always
      image: "nginx:latest"
      ports:
        - "85:85"
      volumes:
        - ./nginx:/etc/nginx/conf.d
      networks:
        - web_network
      depends_on:
        - django_fintech_enterprise_container

  db:
#     image: postgres
#     volumes:
#       - ./data/db:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=bank1
#       - POSTGRES_USER=joelwembo
#       - POSTGRES_PASSWORD=abcde@12345
#       - POSTGRES_PORT=5433
#     expose:
#       - "5433"
#     ports:
#       - "5433"

    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "fintech_enterpriseDB"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
#    ports:
#      - '3306:3306'
#    expose:
#       - 3306
    volumes:
      - ./data/mysql/db:/var/lib/mysql

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge



