apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: DJANGO-docker
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31009
  selector:
    app: django-docker