# Generated by Django 4.0.4 on 2022-06-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('ptype', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('cost', models.FloatField()),
                ('revenue', models.FloatField()),
                ('profit', models.FloatField()),
            ],
        ),
    ]
