# Generated by Django 4.0.4 on 2022-06-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_sales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['cost']},
        ),
    ]
