# Generated by Django 4.0.4 on 2022-08-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_remove_author_headshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
