# Generated by Django 4.0.4 on 2022-11-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roicalculations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoiInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=200)),
                ('totalinterest', models.CharField(max_length=200)),
                ('ir', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=200)),
                ('totalROIA', models.CharField(max_length=200)),
                ('totalinvest', models.CharField(max_length=200)),
                ('oneROIA', models.CharField(max_length=200)),
                ('oneinterest', models.CharField(max_length=200)),
            ],
        ),
    ]
