# Generated by Django 4.0.4 on 2022-11-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roicalculations', '0002_roiinvestment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roiinvestment',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='roiinvestment',
            table='RoiInvestment',
        ),
    ]
